package mcp

// Method represents the HTTP function to be used in the MCP request.
type Method string

// Methods supported by the MCP server.
const (
	MethodNone Method = ""

	MethodCompleteTimer             Method = "complete-timer"
	MethodCreateComment             Method = "create-comment"
	MethodCreateCompany             Method = "create-company"
	MethodCreateJobRole             Method = "create-jobrole"
	MethodCreateMilestone           Method = "create-milestone"
	MethodCreateProject             Method = "create-project"
	MethodCreateSkill               Method = "create-skill"
	MethodCreateTag                 Method = "create-tag"
	MethodCreateTask                Method = "create-task"
	MethodCreateTasklist            Method = "create-tasklist"
	MethodCreateTeam                Method = "create-team"
	MethodCreateTimelog             Method = "create-timelog"
	MethodCreateTimer               Method = "create-timer"
	MethodCreateUser                Method = "create-user"
	MethodPauseTimer                Method = "pause-timer"
	MethodProjectUsers              Method = "project-users"
	MethodResumeTimer               Method = "resume-timer"
	MethodRetrieveActivities        Method = "retrieve-activities"
	MethodRetrieveComment           Method = "retrieve-comment"
	MethodRetrieveComments          Method = "retrieve-comments"
	MethodRetrieveCompanies         Method = "retrieve-companies"
	MethodRetrieveCompany           Method = "retrieve-company"
	MethodRetrieveFileComments      Method = "retrieve-file-comments"
	MethodRetrieveIndustries        Method = "retrieve-industries"
	MethodRetrieveJobRole           Method = "retrieve-jobrole"
	MethodRetrieveJobRoles          Method = "retrieve-jobroles"
	MethodRetrieveMilestone         Method = "retrieve-milestone"
	MethodRetrieveMilestoneComments Method = "retrieve-milestone-comments"
	MethodRetrieveMilestones        Method = "retrieve-milestones"
	MethodRetrieveNotebookComments  Method = "retrieve-notebook-comments"
	MethodRetrieveProject           Method = "retrieve-project"
	MethodRetrieveProjectActivities Method = "retrieve-project-activities"
	MethodRetrieveProjectMilestones Method = "retrieve-project-milestones"
	MethodRetrieveProjectTasklists  Method = "retrieve-project-tasklists"
	MethodRetrieveProjectTasks      Method = "retrieve-project-tasks"
	MethodRetrieveProjectTimelogs   Method = "retrieve-project-timelogs"
	MethodRetrieveProjectUsers      Method = "retrieve-project-users"
	MethodRetrieveProjects          Method = "retrieve-projects"
	MethodRetrieveSkill             Method = "retrieve-skill"
	MethodRetrieveSkills            Method = "retrieve-skills"
	MethodRetrieveTag               Method = "retrieve-tag"
	MethodRetrieveTags              Method = "retrieve-tags"
	MethodRetrieveTask              Method = "retrieve-task"
	MethodRetrieveTaskComments      Method = "retrieve-task-comments"
	MethodRetrieveTaskTimelogs      Method = "retrieve-task-timelogs"
	MethodRetrieveTasklist          Method = "retrieve-tasklist"
	MethodRetrieveTasklistTasks     Method = "retrieve-tasklist-tasks"
	MethodRetrieveTasklists         Method = "retrieve-tasklists"
	MethodRetrieveTasks             Method = "retrieve-tasks"
	MethodRetrieveTeam              Method = "retrieve-team"
	MethodRetrieveTeams             Method = "retrieve-teams"
	MethodRetrieveTimelog           Method = "retrieve-timelog"
	MethodRetrieveTimelogs          Method = "retrieve-timelogs"
	MethodRetrieveTimer             Method = "retrieve-timer"
	MethodRetrieveTimers            Method = "retrieve-timers"
	MethodRetrieveUser              Method = "retrieve-user"
	MethodRetrieveUsers             Method = "retrieve-users"
	MethodRetrieveUsersWorkload     Method = "retrieve-users-workload"
	MethodUpdateComment             Method = "update-comment"
	MethodUpdateCompany             Method = "update-company"
	MethodUpdateJobRole             Method = "update-jobrole"
	MethodUpdateMilestone           Method = "update-milestone"
	MethodUpdateProject             Method = "update-project"
	MethodUpdateSkill               Method = "update-skill"
	MethodUpdateTag                 Method = "update-tag"
	MethodUpdateTask                Method = "update-task"
	MethodUpdateTasklist            Method = "update-tasklist"
	MethodUpdateTeam                Method = "update-team"
	MethodUpdateTimelog             Method = "update-timelog"
	MethodUpdateTimer               Method = "update-timer"
	MethodUpdateUser                Method = "update-user"
)

// String returns the string representation of the Method.
func (m Method) String() string {
	return string(m)
}
